#!/usr/bin/env bash
# A bash script that--
# Creates the file /var/run/myscript.pid containing its PID

echo "$$" > /var/run/myscript.pid

# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal


# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself
#                   when receiving a SIGQUIT or SIGTERM signal

trap 'echo "I hate the kill command"; sudo rm -rf /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap "rm -rf /var/run/myscript.pid; exit" SIGQUIT

i=0
while [ $i -lt 10 ]
do
	echo "To infinity and beyond"
	sleep 2
done
