#!/usr/bin/env bash
# A bash script that displays To infinity and beyond indefinitely.
# With I am invincible!!! when receiving a SIGTERM signal.
i=0
trap 'echo "I am invincible!!!"' SIGTERM
while [ $i -lt 10 ]
do
	echo "To infinity and beyond"
	sleep 2
done
