#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes
# display hours from 0 to 12
# display minutes from 1 to 59

hour=0
minutes=1

while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    while [ $minutes -le 59 ]; do
	echo "$minutes"
	((minutes++))
    done
    minutes=1
    ((hour++))
done
